# Request: Command to control arm
geometry_msgs/Pose[] target_waypoints   # Desired end effector poses, in sequence

---
# Result: Final status of the arm movement
int32 result_code                       # Result code
int32 SUCCESS = 0
int32 INVALID_GOAL = 1
int32 GOAL_TIMEOUT = 2
int32 WAYPOINT_TIMEOUT = 3
int32 CANCELLED = 4

string result_message                   # Description of the result
geometry_msgs/Pose final_pose           # Final end effector pose achieved

---
# Feedback: Progress updates during arm movement
int32 current_waypoint_index            # Index of the current waypoint being approached
geometry_msgs/Pose current_pose         # Current end effector pose
